// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwAvTM_PZKjZijaHbHn2FOfU392J5_V2M',
    appId: '1:980930861095:web:e2fb823d6f6eabe65e5602',
    messagingSenderId: '980930861095',
    projectId: 'expenseapp-ceb9c',
    authDomain: 'expenseapp-ceb9c.firebaseapp.com',
    storageBucket: 'expenseapp-ceb9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnZTpCzgt1WmemBho3pDrkS_D-V8jkUFU',
    appId: '1:980930861095:android:9434d40381303ec05e5602',
    messagingSenderId: '980930861095',
    projectId: 'expenseapp-ceb9c',
    storageBucket: 'expenseapp-ceb9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZmwGBBb-ByeyoL6InKh26T3-zEl-NNb4',
    appId: '1:980930861095:ios:b85ebf7afe6a74e35e5602',
    messagingSenderId: '980930861095',
    projectId: 'expenseapp-ceb9c',
    storageBucket: 'expenseapp-ceb9c.appspot.com',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZmwGBBb-ByeyoL6InKh26T3-zEl-NNb4',
    appId: '1:980930861095:ios:445c349a68120af95e5602',
    messagingSenderId: '980930861095',
    projectId: 'expenseapp-ceb9c',
    storageBucket: 'expenseapp-ceb9c.appspot.com',
    iosBundleId: 'com.example.expenseApp.RunnerTests',
  );
}
